#!/usr/bin/python

import re
import sys
import xmlrpclib
import resource_manager
from resource_manager import *
from optparse import OptionParser

def main():

	print "METALEUCA DESCRIBE SYSTEM USERS"

	parser = OptionParser()
	parser.add_option("-u", "--user", dest="user", help="user name")
	(options, args) = parser.parse_args()

	rmanager = ResourceManager();

	if options.user is None:
		options.user = "_ALL"

	print rmanager.display_user_by_name(options.user)

if __name__ == "__main__":
    main()
    exit

