#!/usr/bin/python

import re
import sys
import xmlrpclib
import commands
import resource_manager
from resource_manager import *
from optparse import OptionParser

def main():

	print "METALEUCA DESCRIBE INSTANCE"

	parser = OptionParser()
	parser.add_option("-u", "--user", dest="user", help="user name")
	(options, args) = parser.parse_args()

	rmanager = ResourceManager();

	if options.user is None:
		print "Need Input user: -u <user>"
		exit()

	if options.user == "_ALL":
		print "Invalid Input user: " + options.user
		exit()

	system_buf =  rmanager.display_user_by_name(options.user)

	system_list = system_buf.split('\n')
	for system in system_list:
		ip = system.split()[0]

		temp_buf = commands.getoutput("./metaleuca-describe-systems | grep " + ip)
		if len(temp_buf) > 0:
			instance_list = temp_buf.split()
			name = instance_list[1]
			profile = instance_list[9]
			status = "unknown"
			if str(instance_list[13]) == "True":
				status = "pending"
			else:
				status = "running"

			print "INSTANCE " + name + " " + profile + " " + ip + " " + status



if __name__ == "__main__":
    main()
    exit

