#!/usr/bin/python

import re
import sys
import xmlrpclib
import metaleuca
from metaleuca import *
from optparse import OptionParser

def cb(option, opt_str, value, parser):
        args=[]
        for arg in parser.rargs:
                if arg[0] != "-":
                        args.append(arg)
                else:
                        del parser.rargs[:len(args)]
                        break
        if getattr(parser.values, option.dest):
                args.extend(getattr(parser.values, option.dest))
        setattr(parser.values, option.dest, args)

def main():

	print "METALEUCA RELEASE SYSTEMS"

	parser = OptionParser()
	parser.add_option("-u", "--user", dest="user", help="user name")
	parser.add_option("-i", "--ip", action="callback", callback=cb, dest="ip", help="ip")
	(options, args) = parser.parse_args()

	if options.user is not None:
		print commands.getoutput("perl /home/qa-server/lib/machine_pool_manager/free_all_machines_by_owner.pl " + options.user)
	else:
		if options.ip is None:
			print "Need Input ip; Use --help Option"
			exit()

		release_list = ' '.join(options.ip)
		print release_list

		print commands.getoutput("perl /home/qa-server/lib/machine_pool_manager/free_machine.pl " + release_list)

	exit()

if __name__ == "__main__":
    main()
    exit

