#!/usr/bin/python

import re
import sys
import xmlrpclib
import metaleuca
from metaleuca import *

def main():

	metaleuca = Metaleuca();
	server, token = metaleuca.connect()

	print "DISPLAY DISTROS"
	metaleuca.display_distros(server)

if __name__ == "__main__":
    main()
    exit

